################  build stage  ################
FROM node:20-alpine AS builder
WORKDIR /app
COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile
COPY tsconfig.json ./
COPY src ./src
RUN yarn build

################  runtime stage  ################
FROM node:20-alpine
ENV NODE_ENV=production
WORKDIR /app
COPY --from=builder /app/package.json ./
COPY --from=builder /app/yarn.lock ./
RUN yarn install --frozen-lockfile --production --ignore-scripts
COPY --from=builder /app/dist ./dist

EXPOSE 8080
CMD ["node", "dist/mcp.js"]
